version: 2.1
jobs:
  build:
    working_directory: /app
    docker:
      - image: circleci/gcc:latest

    steps:
      - checkout

      # Install dependencies
      - run:
          name: Install CMake
          command: sudo apt-get update && sudo apt-get install -y cmake

      # Build the project
      - run:
          name: Build project
          command: |
            mkdir build
            cd build
            cmake ..
            make

      # Run tests
      - run:
          name: Run tests
          command: |
            cd build
            ctest --output-on-failure
