version: 2.1
jobs:
  build:
    docker:
      - image: ubuntu:latest

    steps:
      - checkout


    steps:
      - checkout

      # Install dependencies
      - run:
          name: Install CMake
          command: sudo apt-get update && sudo apt-get install -y gcc cmake

      # Build the project
      - run:
          name: Build project
          command: |
            mkdir build
            cd build
            cmake ..
            make

      # Run tests
      - run:
          name: Run tests
          command: |
            cd build
            ctest --output-on-failure


